name: Rpg
version: '${project.version}'
main:  project.rpg.Rpg
api-version: 1.18
authors: [ Cucumbersaurus, Behappy ]
libraries:
  - io.github.monun:kommand-core:2.11.0
  - io.github.monun:invfx:3.1.0
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.21
  - org.jetbrains.kotlin:kotlin-reflect:1.5.21
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0

commands:
  quests:
    description: /quests true 또는 /quests false 로 메뉴 표시
  savef:
    description: /save status
  status:
    description: status 커멘드
    usage: "Usage: /<command> [info/add]"
  test:
  titleTest:
  testItem:
  skill:
    description: skill 커멘드
    usage: "Usage: /<command> add [스킬이름]"
    aliases: s
  menu:
  craft:
  level:
  friend:
    description: friend 커멘드
    usage: "Usage: /<command> [add/accept] [사람이름]"
    aliases: p