name: Rpg
version: $version
main: project.rpg.Rpg
api-version: $apiVersion
authors: [ Cucumbersaurus, Behappy ]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion
  - org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3

  - org.jetbrains.exposed:exposed-core:$exposedVersion
  - org.jetbrains.exposed:exposed-jdbc:$exposedVersion
  - org.jetbrains.exposed:exposed-json:$exposedVersion
  - org.jetbrains.exposed:exposed-kotlin-datetime:0.46.0
  - org.xerial:sqlite-jdbc:3.41.2.2

  - io.typst:bukkit-kotlin-serialization:1.0.0

  - io.github.monun:heartbeat-coroutines:0.0.5
  - io.github.monun:kommand-core:3.1.7

commands:
  quests:
    description: /quests true [문자열] 또는 /quests false 로 메뉴 표시
    usage: "/quests true [문자열]\n/quests false"
    aliases: [ 퀘스트, 볃ㄴㅅㄴ ]

  saveFile:
    description: /save

  status:
    description: status 커멘드
    usage: "Usage: /<command> [info/add]"

  user:

  titleTest:

  getItem:
    aliases: [ 아이템, ㅑㅅ드 ]

  menu:
    aliases: [ 메뉴, ㅡ두ㅕ ]
    permission: all

  craft:
    aliases: [ 제작, ㅊㄱㅁㄽ ]
    permission: all

  level:
    aliases: [ 레벨, ㅣㄷㅍ디 ]

  friend:
    description: friend 커멘드
    usage: "Usage: /<command> [add/accept] [사람이름]"
    aliases: [ frn, 친구, ㄹ갸둥 ]
    permission: all

  mob:

  insertsql:

  serialize:
