name: Rpg
version: '${project.version}'
main: project.rpg.Rpg
api-version: 1.20
authors: [ Cucumbersaurus, Behappy ]
libraries:
  - io.github.monun:kommand-core:3.1.7
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.20
  - org.jetbrains.kotlin:kotlin-reflect:1.5.21
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0
  - org.jetbrains.exposed:exposed-core:0.40.1
  - org.jetbrains.exposed:exposed-jdbc:0.40.1
  - org.xerial:sqlite-jdbc:3.39.3.0
  - io.github.monun:heartbeat-coroutines:0.0.5

commands:
  quests:
    description: /quests true [문자열] 또는 /quests false 로 메뉴 표시
    usage: "/quests true [문자열]\n/quests false"
    aliases: [ 퀘스트, 볃ㄴㅅㄴ ]

  saveFile:
    description: /save

  status:
    description: status 커멘드
    usage: "Usage: /<command> [info/add]"

  user:

  titleTest:

  getItem:
    aliases: [ 아이템, ㅑㅅ드 ]

  menu:
    aliases: [ 메뉴, ㅡ두ㅕ ]
    permission: all

  craft:
    aliases: [ 제작, ㅊㄱㅁㄽ ]
    permission: all

  level:
    aliases: [ 레벨, ㅣㄷㅍ디 ]

  friend:
    description: friend 커멘드
    usage: "Usage: /<command> [add/accept] [사람이름]"
    aliases: [ frn, 친구, ㄹ갸둥 ]
    permission: all

  mob:

  insertsql:

  serialize:
