name: Rpg
version: '${project.version}'
main: rpgProject.rpg.Rpg
api-version: 1.18
authors: [ Cucumbersaurus, Behappy ]

commands:
  quests:
    description: /quests true 또는 /quests false 로 메뉴 표시
    true:
    false:
